<head>   
    <META NAME="Description" CONTENT=""/>
    <META NAME="Keywords" CONTENT=""/>
</head>
<?php
    include('connection/header.php');
 ?>
<style>
body{
    background: white!important;
    
}

.li1{
    
    margin-left: 25px!important;
}
.li2{
    
    margin-left: 50px!important;
}
</style>
<div class="col-md-12">
<!-- start ad panle section -->
      <section class="ad-panel">
        <img src="img/collages_update.jpg" style="width: 100%;">
      </section>
      <!-- End ad panle section -->
      <section class="free-text">
        <div class="text-center free-text" style="margin-top: -70px;">
          <h3>Privacy Policy</h3>
        </div>
       
<p style="margin-bottom:5.0pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Introduction</span></span></span></b></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Eduguide Searchurcollege Pvt Ltd our affiliated companies worldwide, are committed to respecting your online privacy and recognize your need for appropriate protection and management of personally identifiable information (&quot;Personal Information&quot;) you share with us, in-line with the applicable data protection laws and regulations.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">This Policy is subject to the terms of the Site Policy (Terms of Use) of Searchurcollege.com and the Application. This policy applies to those who register on the Platform (as defined in the Terms of Use) provided by the Searchurcollege.com, in connection with use of our services, or whose information Searchurcollege.com otherwise receives in connection with its services (such as but not limited to contact information of individuals associated with Searchurcollege.com including partner colleges/ educational institutes etc.)</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Personal information (PI) - means any information relating to an identified or identifiable living person. In particular using a common identifier such as a name, an identification number, location data, an online identifier or one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person or any other piece of information as per applicable laws and regulations.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:5.0pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Information collection</span></span></span></b></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">We collect information about you or your usage to provide better services to all of our users. We collect information in the following ways:</span></span></span></span></span></span></p>

<ol style="list-style: circle;">
	<li class="li1"  style="margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Many of our services require you to register/sign up for an account on Searchurcollege.com. When you do, we will ask for personal information, such as, but not limited to your name, email address and telephone number to create/update your account.</span></span></span></span></span></span></span></li>
	<li style="margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">To provide you additional services, we may collect your profile information such as, but not limited to education background, work experience, date of birth.</span></span></span></span></span></span></span></li>
	<li style="margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">We collect information about the services that you use and how you use them such as, but not limited to log information and location information.</span></span></span></span></span></span></span></li>
	<li style="margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">We may collect your personal information such as but not limited to bank details, passport details to assist for study abroad program which includes services like Letter of recommendation, student profile and student visa.</span></span></span></span></span></span></span></li>
	<li style="margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">When you communicate with Searchurcollege.com or its Application or use the Searchurcollege.com platform to communicate with other Members (such as advertisers, colleges/ institutes, etc.), we collect information about your communication and any other additional information you choose to provide.</span></span></span></span></span></span></span></li>
</ol>

<p align="justify" style="margin-bottom:5.0pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Processing personal information</span></span></span></b></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Searchurcollege.com may process your Personal Information for the following purposes:</span></span></span></span></span></span></p>

<ol style="list-style: circle;">
	<li class="li1" style="margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">We use information collected from cookies and other technologies, like pixel tags, to improve your user experience and the overall quality of our services. When showing you tailored ads, we will not associate an identifier from cookies or similar technologies with sensitive categories, such as those based on race, religion, sexual orientation or health.</span></span></span></span></span></span></span></li>
	<li style="margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Our automated systems analyse your content to provide you customised search results, recommendations and specific promotions and offers</span></span></span></span></span></span></span></li>
	<li style="margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Send alerts and newsletter(s) to you (Provided you subscribe to the same. To unsubscribe, please visit your account settings)</span></span></span></span></span></span></span></li>
	<li style="margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Improving our website and its content to provide better features and services</span></span></span></span></span></span></span></li>
	<li style="margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Conducting market research and surveys with the aim of improving our products and services.</span></span></span></span></span></span></span></li>
	<li style="margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Sending you information about our products and services for marketing purposes and promotions.</span></span></span></span></span></span></span></li>
	<li style="margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Preventing, detecting, investigating and prosecuting crimes (including but not limited to fraud and other financial crimes) in any jurisdiction, identity verification, government sanctions screening and due diligence checks</span></span></span></span></span></span></span></li>
	<li style="margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Establishing, exercising or defending legal rights in connection with legal proceedings (including any prospective legal proceedings) and seeking professional or legal advice in relation to such legal proceedings.</span></span></span></span></span></span></span></li>
</ol>

<p align="justify" style="margin-bottom:5.0pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Cookies and Other Tracking Technologies</span></span></span></b></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Some of our Web pages utilize &quot;cookies&quot; and other tracking technologies. A &quot;cookie&quot; is a small text file that may be used, for example, to collect your information about Website activity. Some cookies and other technologies may serve to recall Personal Information previously indicated by a Web user. Most browsers allow you to control cookies, including whether or not to accept them and how to remove them.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">You may set most browsers to notify you if you receive a cookie, or you may choose to block cookies with your browser, but please note that if you choose to erase or block your cookies, you will need to re-enter your original user ID and password to gain access to certain parts of the Web site and some sections/features of the site may not work.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Tracking technologies may record information such as Internet domain and host names; Internet protocol (IP) addresses; browser software and operating system types; click stream patterns; and dates and times that our site has accessed.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Our use of cookies and other tracking technologies allows us to improve our Web site and your Web experience. We may also analyse information that does not contain Personal Information for trends and statistics.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:5.0pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Third Party Services</span></span></span></b></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Third parties provide certain services available on Searchurcollege.com on Eduguige Searchurcollege Pvt.Ltd behalf. Searchurcollege.com may provide information, including Personal Information, that &lsquo;Searchurcollege.com collects on the Web to third-party service providers to help us deliver programs, products, information, and services. Service providers are also an important means by which Searchurcollege.com maintains its Web site and mailing lists. Searchurcollege.com will take reasonable steps to ensure that these third-party service providers are obligated to protect Personal Information on Searchurcollege.com behalf.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Searchurcollege.com does not intend to transfer Personal Information without your consent to third parties unless such transfer is required for providing relevant services or for purposes legal purposes.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">When you are in a relationship with Searchurcollege.com, your personal information may be transferred to geographies outside India, for the purposes mentioned in this policy or to their local service providers for support in the pursuance of such purposes. Transfers outside India are covered by standard data protection laws.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Please be aware that Searchurcollege.com sometimes contains links to other sites that are not governed by this privacy policy. Visitors to Our Site may be directed to third-party sites for more information, such as advertisers, blogs, content sponsorships, vendor services, social networks, etc.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Searchurcollege.com makes no representations or warranties regarding how your information is stored or used on third-party servers. We recommend that you review the privacy statement of each third-party site linked from Our Site to determine their use of your personal information.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:5.0pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Children</span></span></span></b></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">To use the Site you agree that you must be of minimum age 18 years or older.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">In case you are resident of the European Union, the minimum age for these purposes shall be 16, however if local laws require that you must be older in order for Searchurcollege.com to lawfully provide the services on the Site to you then that older age shall apply as the applicable minimum age.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">In all jurisdictions outside the European Union, if you are under the age of 18 or the age of majority in your jurisdiction, you must use Searchurcollege.com under the supervision of your parent, legal guardian or responsible adult.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:5.0pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Information Sharing</span></span></span></b></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">We restrict access to your Personal Information to employees who we believe reasonably need to know/or that information in order to fulfil their jobs to provide, operate, develop, or improve our products or services.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Searchurcollege.com does not rent, sell, or share personal information about you with other people or non-affiliated companies except:</span></span></span></span></span></span></p>

<ol style="list-style: circle;">
	<li class="li1" style="margin:0in 0in 10pt"><p align="justify"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">to provide products or services you&#39;ve requested,</span></span></span></span></span></span></span></p></li>
	<li class="li1" style="margin:0in 0in 10pt"><p align="justify"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">when we have your permission,</span></span></span></span></span></span></span></p></li>
	<li class="li1" style="margin:0in 0in 10pt"><p align="justify"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">or under the following circumstances:</span></span></span></span></span></span></span></p></li>
</ol>

<ol style="list-style: circle;">
	<li class="li2" style="margin:0in 0in 10pt"><p align="justify"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">We provide the information to trusted partners who work on behalf of or with &lsquo;Eduguide Searchurcollege Pvt. Ltd&rsquo; under confidentiality agreements. These companies may use your personal information to help Searchurcollege.com communicate with you about offers from &lsquo;Searchurcollege.com and our marketing partners. However, these companies do not have any independent right to share this information.</span></span></span></span></span></span></span></p></li>
	<li class="li2" style="margin:0in 0in 10pt"><p align="justify"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">We respond to subpoenas, court orders, or legal process, or to establish or exercise our legal rights or defend against legal claims;</span></span></span></span></span></span></span></p></li>
	<li class="li2" style="margin:0in 0in 10pt"><p align="justify"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">We believe it is necessary to share information in order to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of &lsquo;Searchurcollege.com terms of use, or as otherwise required by law.</span></span></span></span></span></span></span></p></li>
	<li class="li2" style="margin:0in 0in 10pt"><p align="justify"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">We transfer information about you if &lsquo;Searchurcolege.com is acquired by or merged with another company. In this event, &lsquo;Searchurcollege.com will notify you before information about you is transferred and becomes subject to a different privacy policy.</span></span></span></span></span></span></span></p></li>
	<li class="li2" style="margin:0in 0in 10pt"><p align="justify"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">We share your personal information with colleges or educational institutions, etc. based on your browsing behaviour or expression of interest regarding courses, specializations and institutions who may further contact you.</span></span></span></span></span></span></span></p></li>
</ol>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Searchurcollege.com&nbsp;displays targeted advertisements based on personal information. Advertisers (including ad serving for example, women aged 18-24 from a particular geographic area.</span></span></span></span></span></span></p>

<ol style="list-style: circle;">
	<li class="li2" style="margin:0in 0in 10pt"><p align="justify"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Searchurcollege.com&nbsp;does not provide any personal information to the advertiser when you interact with or view a targeted ad. However, by interacting with an ad you are consenting to the possibility that the advertiser will make the assumption that you meet the targeting criteria used to display the ad.</span></span></span></span></span></span></span></p></li>
	<li class="li2" style="margin:0in 0in 10pt"><p align="justify"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Searchurcollege.com&nbsp;advertisers include financial service providers (such as banks, insurance agents, stock brokers and mortgage lenders) and non-financial companies (such as stores, airlines, and software companies).</span></span></span></span></span></span></span></p></li>
	<li class="li2" style="margin:0in 0in 10pt"><p align="justify"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">We may share personal information (such as name, mobile number, and email address) with carefully selected education colleges/ educational institutions based on your expression of interest regarding courses, specializations and institutions so that they may consider further marketing campaigns or recruitment measures. Some of these educational institutions may have access to your personal information to verify the status of your application or enrolment. We will inform the education institutions that they are not allowed to use your personal information for any reason other than mentioned above. Users should note however that, how these educational institutions use this data is not governed by our privacy policy. Therefore, we cannot be held responsible for how the data is utilized once it is shared with them. Educational institutions have separate policy practices for which Searchurcollege.com has no responsibility or liability. For further information on how such institutions use your information, please visit the applicable privacy policy of that institution.</span></span></span></span></span></span></span></p></li>
	<li class="li2" style="margin:0in 0in 10pt"><p align="justify"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Searchurcollege.com works with vendors, partners, advertisers, and other service providers in different industries and categories of business. For more information regarding providers of products or services.</span></span></span></span></span></span></span></p></li>
</ol>

<p align="justify" style="margin-bottom:5.0pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Retention of personal information</span></span></span></b></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Your personal information processed by Searchurcollege.com are kept in a form which permits your identification for no longer than is necessary for the purposes for which the personal information are processed in line with legal, regulatory, contractual or statutory obligations as applicable.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">At the expiry of such periods, your personal information will be archived to comply with legal/contractual retention obligations or in accordance with applicable statutory limitation periods.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:5.0pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Personalisation of services</span></span></span></b></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">To the extent permitted by law, Searchurcollege.com may record and monitor your communications with us to ensure compliance with our legal and regulatory obligations and our internal policies. This may include the recording of telephone conversations.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:5.0pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Personalisation of services</span></span></span></b></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">You may have the right to invoke certain rights (as per applicable laws and regulations such as GDPR) in relation to your personal information being processed by the Platform.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">The Platform may be allowed by law, in particular in case of excessive or manifestly unfounded request, to charge a fee for fulfilling your request, subject to applicable conditions.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">You are legally entitled to request details of the personal information we may be holding about you. The Company provides you the ability to keep your personal information accurate and up-to-date. If at any time you would like to rectify, erase or restrict the processing of your personal information, or you would like to obtain confirmation whether or not your personal information is processed by it, access your personal information, exercise your right to data portability or withdraw your consent to processing, please contact us.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:5.0pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Confidentiality and Security</span></span></span></b></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">The security and confidentiality of your Personal Data is important to us and Searchurcollege.com has invested significant resources to protect the safekeeping and confidentiality of your personal data. When using external service providers acting as processors, we require that they adhere to the same standards as Searchurcollege.com. Regardless of where your personal information is transferred or stored, we take all steps reasonably necessary to ensure that personal data is kept secure.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">We have physical, electronic, and procedural safeguards that comply with the laws prevalent in India to protect personal information about you. We seek to ensure compliance with the requirements of the Information Technology Act, 2000 and Rules made there under to ensure the protection and preservation of your privacy.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:5.0pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Social media</span></span></span></b></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Searchurcollege.com operates channels, pages and accounts on some social media sites to inform, assist and engage with you. Searchurcollege.com monitors and records comments and posts made on these channels about Searchurcollege.com in order to improve its products and services. Please note that you must not communicate with Searchurcollege.com through such social media sites the following information:</span></span></span></span></span></span></p>

<ol style="list-style: circle;">
	<li class="li1" style="margin:0in 0in 10pt"><p align="justify"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Sensitive personal data including (i) special categories of personal data meaning any information revealing racial or ethnic origin, political opinions, religious or philosophical beliefs, or trade union membership, and the processing of genetic data, biometric data for the purpose of uniquely identifying a natural person, data concerning health or data concerning a natural person&#39;s sex life or sexual orientation and (ii) other sensitive personal data such as criminal convictions and offences and national identification number ;</span></span></span></span></span></span></span></p></li>
	<li class="li1" style="margin:0in 0in 10pt"><p align="justify"><span style="font-size:11pt"><span style="line-height:normal"><span style="tab-stops:list .5in"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Excessive, inappropriate, offensive or insulting information towards individuals.</span></span></span></span></span></span></span></p></li>
</ol>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Searchurcollege.com is not responsible for any information posted on those sites other than the information posted by its employees on its behalf. Searchurcollege.com is only responsible for its own use of the personal data received through such sites</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:5.0pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Changes to this Privacy Policy</span></span></span></b></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Searchurcollege.com reserves the right to update, change or modify this policy at any time. The policy shall come to effect from the date of such update, change or modification.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:5.0pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Disclaimer</span></span></span></b></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Searchurcollege.com shall not be liable for any loss or damage sustained by reason of any disclosure (inadvertent or otherwise) of any information concerning the user&#39;s account and / or information relating to or regarding online transactions using credit cards / debit cards and / or their verification process and particulars nor for any error, omission or inaccuracy with respect to any information so disclosed and used whether or not in pursuance of a legal process or otherwise. Searchurcollege.com does not store any Credit / Debit card details.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Any other personal information shared by you which is not asked by Searchurcollege.com during registration, either mandatorily or optionally; accounts to wilful and intentional furnishing; and Searchurcollege.com will not be liable for breach of such information.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">If you have any questions regarding this privacy policy or the protection of your personal data, please contact.</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Eduguide Searchurcollege Pvt. Ltd</span></span></span></b></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">B-41, Sector-2, Noida (UP)-201301</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt"><span style="font-size:11pt"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:14pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:#111111">Email: info@searchurcollege.com</span></span></span></span></span></span></p>

<p align="justify" style="margin-bottom:8.35pt; margin:0in 0in 10pt">&nbsp;</p>

<p align="justify" style="margin:0in 0in 10pt">&nbsp;</p>


              


          <div class="clearfix"></div>
        </div>
      </section>

</div>
<?php
    include('footer.php');
?>

